/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalJframe;

import MainFrame.employee_info;
import MainFrame.javaconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author saimonazad
 */
public class NewJInternalFrame extends javax.swing.JInternalFrame {

    String CategoryID=null;
    String SubCategoryID=null;
    String ProductID;
    String ProductNames;
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form NewJInternalFrame
     */
    public NewJInternalFrame() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        FillCombo_cat();
        FillCombo_SubCat();
    }
    private void FillCombo_cat()
    {
        try {
            String sql="SELECT * FROM CATEGORY";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next())
            {
                String name=rs.getString("CategoryTitle");
                Combo_Cat.addItem(name);
            }
        } catch (Exception e) {
        }
    }
     private void FillCombo_SubCat()
    {
        try {
            String sql="SELECT * FROM SUBCATEGORY";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next())
            {
                String name=rs.getString("SubCategoryTitle");
                Combo_SubCat.addItem(name);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        ExpDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mfgDate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        SupplierName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ProductName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AddToTable = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Combo_Cat = new javax.swing.JComboBox<>();
        unit = new javax.swing.JTextField();
        Combo_SubCat = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BarcodeNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PurchaseNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ProductBrand = new javax.swing.JTextField();
        SellPrice = new javax.swing.JTextField();
        PurchasePrice = new javax.swing.JTextField();
        LotNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Employeeid = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        read = new javax.swing.JButton();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();

        jLabel12.setText("Purchase Price");

        jLabel13.setText("Sell Price");

        Quantity.setText("jTextField1");

        ExpDate.setText("jTextField1");

        jLabel14.setText("EXP Date");

        mfgDate.setText("jTextField1");

        jLabel16.setText("MFG Date");

        SupplierName.setText("jTextField1");

        jLabel17.setText("Supplier id");

        ProductName.setText("jTextField1");

        jLabel3.setText("Product Name");

        AddToTable.setText("Add");
        AddToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToTableActionPerformed(evt);
            }
        });

        jLabel4.setText("Brand");

        Combo_Cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        Combo_Cat.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                Combo_CatPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        Combo_Cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_CatActionPerformed(evt);
            }
        });

        unit.setText("jTextField1");

        Combo_SubCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        Combo_SubCat.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                Combo_SubCatPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        Combo_SubCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_SubCatActionPerformed(evt);
            }
        });

        jLabel6.setText("Unit");

        jLabel8.setText("Quantity");

        BarcodeNo.setText("jTextField1");

        jLabel10.setText("Barcode No");

        PurchaseNo.setText("jTextField1");

        jLabel11.setText("Purchase No");

        jLabel1.setText("Category");

        jLabel2.setText("Sub Category");

        ProductBrand.setText("jTextField1");

        SellPrice.setText("jTextField1");

        PurchasePrice.setText("jTextField1");

        LotNo.setText("jTextField1");

        jLabel5.setText("Lot No");

        Employeeid.setText("jTextField1");
        Employeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeidActionPerformed(evt);
            }
        });

        jLabel18.setText("Employee id");

        read.setText("Test read");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        dateChooserCombo2.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo2OnCommit(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(ProductBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Combo_Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_SubCat, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(42, 42, 42)
                                .addComponent(SellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(42, 42, 42)
                                .addComponent(PurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(42, 42, 42)
                                .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(42, 42, 42)
                                .addComponent(mfgDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5)))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LotNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddToTable)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(42, 42, 42)
                                .addComponent(PurchaseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(42, 42, 42)
                                .addComponent(BarcodeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Employeeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(read)
                        .addGap(41, 41, 41)))
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BarcodeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PurchaseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(Employeeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Combo_Cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Combo_SubCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(AddToTable))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mfgDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(75, 75, 75)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LotNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(read)
                .addGap(18, 18, 18)
                .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToTableActionPerformed
        // TODO add your handling code here:
        
         try {
             //Product table insert
           String sql="Insert into PRODUCT (ProductTitle,ProductBrand,SubCategoryID) values(?,?,?)"; 
           pst=conn.prepareStatement(sql);
           ProductNames=ProductName.getText();
           pst.setString(1, ProductNames);
           pst.setString(2, ProductBrand.getText());
           pst.setString(3, SubCategoryID);
           pst.execute();
             System.err.println("Product name :"+ProductNames);
           //JOptionPane.showMessageDialog(null, "Saved");
        String sql3="SELECT * FROM PRODUCT WHERE ProductTitle=?";
        try {
            pst=conn.prepareStatement(sql3);
            pst.setString(1, ProductNames);
            rs=pst.executeQuery();
            if(rs.next())
            {
                ProductID=rs.getString("ProductID");
            }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
             
           
            
           
           
           
           //Stock table insert
           String sql1="Insert into STOCK (ProductID,LotNo,Quantity,SupplierID,BarcodeNo,PurchaseNo,SellPrice,ManufactureDate,ExpDate,EmployeeID,PurchasePrice) values(?,?,?,?,?,?,?,?,?,?,?)"; 
           pst=conn.prepareStatement(sql1);
           pst.setString(1, ProductID);
           pst.setString(2, LotNo.getText());
           pst.setString(3, Quantity.getText());
           
           pst.setString(4, SupplierName.getText());
           pst.setString(5, BarcodeNo.getText());
           pst.setString(6, PurchaseNo.getText());
           pst.setString(7, SellPrice.getText());
           pst.setString(8, mfgDate.getText());
           pst.setString(9, ExpDate.getText());
           pst.setString(10, Employeeid.getText());
           pst.setString(11, PurchasePrice.getText());
           
           pst.execute();
           
        } catch (Exception e) {
        }
         
        
        
        
  

        /* ArrayList<String> numdata = new ArrayList<String>();
        for (int count = 0; count < model.getRowCount(); count++){
            numdata.add(model.getValueAt(count, 0).toString());
        }*/

    }//GEN-LAST:event_AddToTableActionPerformed

    private void Combo_CatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_CatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_CatActionPerformed

    private void Combo_SubCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_SubCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_SubCatActionPerformed

    private void Combo_CatPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_Combo_CatPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp=(String)Combo_Cat.getSelectedItem();
        String sql="SELECT * FROM CATEGORY WHERE CategoryTitle=?";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs=pst.executeQuery();
            if(rs.next())
            {
                CategoryID=rs.getString("CategoryID");
            }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        System.err.println(CategoryID);
    }//GEN-LAST:event_Combo_CatPopupMenuWillBecomeInvisible

    private void Combo_SubCatPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_Combo_SubCatPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp=(String)Combo_SubCat.getSelectedItem();
        String sql="SELECT * FROM SUBCATEGORY WHERE SubCategoryTitle=?";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs=pst.executeQuery();
            if(rs.next())
            {
                SubCategoryID=rs.getString("SubCategoryID");
            }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        System.err.println(SubCategoryID);
    }//GEN-LAST:event_Combo_SubCatPopupMenuWillBecomeInvisible

    private void EmployeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeidActionPerformed

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
        // TODO add your handling code here:
         
        
        
    }//GEN-LAST:event_readActionPerformed

    private void dateChooserCombo2OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo2OnCommit
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_dateChooserCombo2OnCommit


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AddToTable;
    public javax.swing.JTextField BarcodeNo;
    public javax.swing.JComboBox<String> Combo_Cat;
    public javax.swing.JComboBox<String> Combo_SubCat;
    public javax.swing.JTextField Employeeid;
    public javax.swing.JTextField ExpDate;
    public javax.swing.JTextField LotNo;
    public javax.swing.JTextField ProductBrand;
    public javax.swing.JTextField ProductName;
    public javax.swing.JTextField PurchaseNo;
    public javax.swing.JTextField PurchasePrice;
    public javax.swing.JTextField Quantity;
    public javax.swing.JTextField SellPrice;
    public javax.swing.JTextField SupplierName;
    public datechooser.beans.DateChooserCombo dateChooserCombo2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JTextField mfgDate;
    public javax.swing.JButton read;
    public javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables
}
